Import('env commons_path bioinfo_path math_path')

prog = env.Program('hpg-var-haplo', 
             source = [Glob('*.c'), Glob('../*.c'),
                       "%s/libcommon.a" % commons_path,
                       "%s/libbioinfo.a" % bioinfo_path,
                       "%s/libhpgmath.a" % math_path
                      ]
           )

Return("prog")
